### ISSUE TITLE
哥哥好

### ISSUE THREAD

**Issue by xiaopohou** [myvas/TencentSms#2]
你的这个项目写的不错，你的其他项目也写的挺接地气的，我关于你那个短信接口项目里的一段代码不理解：

 public async Task<bool> SendSmsAsync(string mobile, string content)
        {
            await Task.FromResult(0);

  为什么要写一个   await Task.FromResult(0); 这个呢？

**Comment by huangxiangyao** [comment]
不好意思，回复晚了。
那是因为：在返回类型为 async Task 的函数中，如果没有 await 语句就会有一条警告。这条语句是为了消除这条警告。
